package Module1SubModules;

import SystemInstance.MysqlConnect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author iRHONman
 */
public class AddPatient extends javax.swing.JFrame
{

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stmt = null;

    /**
     * Creates new form AddPatient
     */
    public AddPatient()
    {
        initComponents();
        conn = MysqlConnect.ConnectDB();
        Active.setVisible(false);
        time.setVisible(false);
        date.setVisible(true);
        date();
        id.setVisible(false);
        remarks.setVisible(false);
        auto_PATIENT_number();
        int timecount = 0;

        new Thread()
        {

            public void run()

            {
                while (timecount == 0)
                {
                    Calendar cal = new GregorianCalendar();

                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int AM_PM = cal.get(Calendar.AM_PM);

                    String day_night = "";

                    if (AM_PM == 1)
                    {
                        day_night = "PM";
                    } else
                    {
                        day_night = "AM";
                    }
                    String count = hour + ":" + min + ":" + sec + " " + day_night;
                    time.setText(count);
                }
            }
        }.start();

    }

    public void date()
    {
        Thread clock = new Thread()
        {
            public void run()
            {
                for (;;)
                {
                    Calendar calen = GregorianCalendar.getInstance();
                    int AM_PM = calen.get(Calendar.AM_PM);

                    String[] days = new String[]
                    {
                        "", "", "", "", "", "", ""
                    };
                    String day_night = "";
                    if (AM_PM == 1)
                    {
                        day_night = "PM";
                    } else
                    {
                        day_night = "AM";
                    }

                    //  time1.setText(hour+":"+mins+":"+secs); 
                    date.setVisible(false);
                    int mons = calen.get(Calendar.MONTH);
                    int day = calen.get(Calendar.DAY_OF_MONTH);
                    int yr = calen.get(Calendar.YEAR);
                    date.setText(days[calen.get(Calendar.DAY_OF_WEEK) - 1] + " " + (mons + 1) + "/" + day + "/" + yr);
                    try
                    {
                        sleep(1000);
                    } catch (InterruptedException ex)
                    {

                    }
                }
            }
        };

        clock.start();
    }

    public void auto_PATIENT_number()
    {

        try
        {
            String sql = "SELECT Count(Patient_ID)AS no FROM Core1_pr_PatientRegistration";
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = stmt.executeQuery(sql);

            while (rs.next())
            {

                if (rs.first() == false)
                {
                    id.setText("1");
                } else
                {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 3 - nolong; a++)
                    {
                        no = "" + no;
                    }
                    id.setText(no);
                }
            }

        } catch (Exception e)
        {
            System.out.println(e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sub_module_1_btn6 = new javax.swing.JButton();
        addpatient = new javax.swing.JPanel();
        sub_module_1_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        mi = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        MobileNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel41 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        BusinessPhone = new javax.swing.JTextField();
        bday = new com.toedter.calendar.JDateChooser();
        last = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        middle = new javax.swing.JLabel();
        bdate = new javax.swing.JLabel();
        Occ = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        error11 = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        txt_noAddress1 = new javax.swing.JTextField();
        jLabel154 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        MaritalStatus = new javax.swing.JComboBox<>();
        Nationality = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        SpouseName = new javax.swing.JTextField();
        MaidenName = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Company = new javax.swing.JTextField();
        Religion = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        PlaceBirth = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        Hobby = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        Contraception = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        error4 = new javax.swing.JLabel();
        hobby = new javax.swing.JLabel();
        place = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        facebook = new javax.swing.JTextField();
        Twitter = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Skype = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Notes = new javax.swing.JTextArea();
        note = new javax.swing.JLabel();
        Active = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        id = new java.awt.Label();
        remarks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub_module_1_btn6.setBackground(new java.awt.Color(153, 153, 153));
        sub_module_1_btn6.setText("Back");
        sub_module_1_btn6.setToolTipText("Sub Module 1");
        sub_module_1_btn6.setBorder(null);
        sub_module_1_btn6.setBorderPainted(false);
        sub_module_1_btn6.setContentAreaFilled(false);
        sub_module_1_btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_module_1_btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub_module_1_btn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sub_module_1_btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sub_module_1_btn6MouseExited(evt);
            }
        });
        sub_module_1_btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_module_1_btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(sub_module_1_btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 60, 30));

        addpatient.setBackground(new java.awt.Color(255, 255, 255));
        addpatient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        addpatient.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                addpatientAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addpatient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub_module_1_btn.setBackground(new java.awt.Color(153, 153, 153));
        sub_module_1_btn.setText("Save & Close");
        sub_module_1_btn.setToolTipText("Sub Module 1");
        sub_module_1_btn.setBorder(null);
        sub_module_1_btn.setBorderPainted(false);
        sub_module_1_btn.setContentAreaFilled(false);
        sub_module_1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_module_1_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub_module_1_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sub_module_1_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sub_module_1_btnMouseExited(evt);
            }
        });
        sub_module_1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_module_1_btnActionPerformed(evt);
            }
        });
        addpatient.add(sub_module_1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane7.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 20));

        jLabel2.setText("Middle Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 20));

        jLabel3.setText("Gender:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 20));

        jLabel5.setText("Last Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        jLabel6.setText("Birth Date:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 20));

        jLabel7.setText("Occupation:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 20));

        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 250, 20));

        mi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                miKeyTyped(evt);
            }
        });
        jPanel2.add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 250, 20));

        occupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                occupationKeyTyped(evt);
            }
        });
        jPanel2.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 250, 20));

        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnameKeyTyped(evt);
            }
        });
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 250, 20));

        PhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneNumberKeyTyped(evt);
            }
        });
        jPanel2.add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 250, 20));

        jLabel9.setText("Phone Number:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 20));

        MobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MobileNumberKeyTyped(evt);
            }
        });
        jPanel2.add(MobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 250, 20));

        jLabel10.setText("Mobile Number:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, 20));

        jRadioButton1.setText("FEMALE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 70, 20));

        jRadioButton5.setText("MALE");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, 20));

        jLabel41.setText("Emai:");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 20));

        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailKeyTyped(evt);
            }
        });
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 250, 20));

        jLabel46.setText("Business Phone:");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 110, 20));

        BusinessPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusinessPhoneKeyTyped(evt);
            }
        });
        jPanel2.add(BusinessPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 250, 20));
        jPanel2.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 250, -1));

        last.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        last.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(last, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 190, 20));

        first.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        first.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 190, 20));

        middle.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        middle.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(middle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 190, 20));

        bdate.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        bdate.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 190, 20));

        Occ.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        Occ.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(Occ, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 190, 20));

        email.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        email.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 190, 20));

        error11.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        error11.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(error11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 190, 20));

        number.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        number.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 190, 30));

        txt_noAddress1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_noAddress1KeyReleased(evt);
            }
        });
        jPanel2.add(txt_noAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 250, 20));

        jLabel154.setText("Address:");
        jPanel2.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 50, 20));

        jLabel4.setText("Age");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 40, 20));

        jTabbedPane7.addTab("Patient", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("Marital Status:");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        MaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Widdowed", "Separated", "Divorce" }));
        jPanel5.add(MaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 250, -1));

        Nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghan", "Albanian", "Algerian", "American", "Andorran", "Angolan", "Antiguans", "Argentinean", "Armenian", "Australian", "Austrian", "Azerbaijani", "Bahamian", "Bahraini", "Bangladeshi", "Barbadian", "Barbudans", "Batswana", "Belarusian", "Belgian", "Belizean", "Beninese", "Bhutanese", "Bolivian", "Bosnian", "Brazilian", "British", "Bruneian", "Bulgarian", "Burkinabe", "Burmese", "Burundian", "Cambodian", "Cameroonian", "Canadian", "Cape Verdean", "Central African", "Chadian", "Chilean", "Chinese", "Colombian", "Comoran", "Congolese", "Costa Rican", "Croatian", "Cuban", "Cypriot", "Czech", "Danish", "Djibouti", "Dominican", "Dutch", "East Timorese", "Ecuadorean", "Egyptian", "Emirian", "Equatorial Guinean", "Eritrean", "Estonian", "Ethiopian", "Fijian", "Filipino", "Finnish", "French", "Gabonese", "Gambian", "Georgian", "German", "Ghanaian", "Greek", "Grenadian", "Guatemalan", "Guinea-Bissauan", "Guinean", "Guyanese", "Haitian", "Herzegovinian", "Honduran", "Hungarian", "I-Kiribati", "Icelander", "Indian", "Indonesian", "Iranian", "Iraqi", "Irish", "Israeli", "Italian", "Ivorian", "Jamaican", "Japanese", "Jordanian", "Kazakhstani", "Kenyan", "Kittian and Nevisian", "Kuwaiti", "Kyrgyz", "Laotian", "Latvian", "Lebanese", "Liberian", "Libyan", "Liechtensteiner", "Lithuanian", "Luxembourger", "Macedonian", "Malagasy", "Malawian", "Malaysian", "Maldivian", "Malian", "Maltese", "Marshallese", "Mauritanian", "Mauritian", "Mexican", "Micronesian", "Moldovan", "Monacan", "Mongolian", "Moroccan", "Mosotho", "Motswana", "Mozambican", "Namibian", "Nauruan", "Nepalese", "New Zealander", "Ni-Vanuatu", "Nicaraguan", "Nigerian", "Nigerien", "North Korean", "Northern Irish", "Norwegian", "Omani", "Pakistani", "Palauan", "Panamanian", "Papua New Guinean", "Paraguayan", "Peruvian", "Polish", "Portuguese", "Qatari", "Romanian", "Russian", "Rwandan", "Saint Lucian", "Salvadoran", "Samoan", "San Marinese", "Sao Tomean", "Saudi", "Scottish", "Senegalese", "Serbian", "Seychellois", "Sierra Leonean", "Singaporean", "Slovakian", "Slovenian", "Solomon Islander", "Somali", "South African", "South Korean", "Spanish", "Sri Lankan", "Sudanese", "Surinamer", "Swazi", "Swedish", "Swiss", "Syrian", "Taiwanese", "Tajik", "Tanzanian", "Thai", "Togolese", "Tongan", "Trinidadian or Tobagonian", "Tunisian", "Turkish", "Tuvaluan", "Ugandan", "Ukrainian", "Uruguayan", "Uzbekistani", "Venezuelan", "Vietnamese", "Welsh", "Yemenite", "Zambian", "Zimbabwean" }));
        jPanel5.add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 250, -1));

        jLabel32.setText("Nationality:");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 20));

        jLabel34.setText("Spouse Name:");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 20));

        SpouseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SpouseNameKeyTyped(evt);
            }
        });
        jPanel5.add(SpouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 250, 20));

        MaidenName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MaidenNameKeyTyped(evt);
            }
        });
        jPanel5.add(MaidenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 250, 20));

        jLabel35.setText("Maiden Name:");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 20));

        jLabel36.setText("Company:");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 20));

        Company.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CompanyMouseReleased(evt);
            }
        });
        Company.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CompanyKeyTyped(evt);
            }
        });
        jPanel5.add(Company, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 250, 20));

        Religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roman Catholic", "Protestants", "Muslims", "Iglesia ni Cristo", "Buddhists" }));
        jPanel5.add(Religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 250, -1));

        jLabel37.setText("Religion:");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 20));

        PlaceBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PlaceBirthKeyTyped(evt);
            }
        });
        jPanel5.add(PlaceBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 20));

        jLabel38.setText("Place of Birth:");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 20));

        Hobby.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HobbyKeyTyped(evt);
            }
        });
        jPanel5.add(Hobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 250, 20));

        jLabel39.setText("Hobby:");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 20));

        Contraception.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContraceptionKeyTyped(evt);
            }
        });
        jPanel5.add(Contraception, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 250, 20));

        jLabel40.setText("Contraception:");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, 20));

        error4.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        error4.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(error4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, 20));

        hobby.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        hobby.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(hobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 190, 20));

        place.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        place.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 190, 20));

        jTabbedPane7.addTab("More Details", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setText("Facebook:");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        facebook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                facebookKeyTyped(evt);
            }
        });
        jPanel6.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 250, 20));

        Twitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TwitterKeyTyped(evt);
            }
        });
        jPanel6.add(Twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 250, 20));

        jLabel44.setText("Twitter:");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 20));

        jLabel45.setText("Skype:");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 20));

        Skype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SkypeKeyTyped(evt);
            }
        });
        jPanel6.add(Skype, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 250, 20));

        jTabbedPane7.addTab("Social", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Notes.setColumns(20);
        Notes.setRows(1000);
        Notes.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Notes);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 510));

        note.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        note.setForeground(new java.awt.Color(204, 0, 0));
        jPanel7.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 190, 20));

        jTabbedPane7.addTab("Notes", jPanel7);

        jPanel1.add(jTabbedPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 570));

        addpatient.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 590, 570));

        Active.setText("Active");
        addpatient.add(Active, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 80, 20));

        time.setText("Time");
        addpatient.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 80, 20));

        date.setText("date");
        addpatient.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 80, 20));

        id.setText("label1");
        addpatient.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 50, -1));

        remarks.setText("New");
        addpatient.add(remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        getContentPane().add(addpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sub_module_1_btnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sub_module_1_btnMouseClicked
    {//GEN-HEADEREND:event_sub_module_1_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_module_1_btnMouseClicked

    private void sub_module_1_btnMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sub_module_1_btnMouseEntered
    {//GEN-HEADEREND:event_sub_module_1_btnMouseEntered
        sub_module_1_btn.setOpaque(true);
        sub_module_1_btn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_sub_module_1_btnMouseEntered

    private void sub_module_1_btnMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sub_module_1_btnMouseExited
    {//GEN-HEADEREND:event_sub_module_1_btnMouseExited
        sub_module_1_btn.setOpaque(false);
    }//GEN-LAST:event_sub_module_1_btnMouseExited

    private void sub_module_1_btnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sub_module_1_btnActionPerformed
    {//GEN-HEADEREND:event_sub_module_1_btnActionPerformed
        String aa = this.lname.getText();
        String bb = this.fname.getText();
        String cc = this.mi.getText();
        String dd = this.bday.getDateFormatString();
        String ee = this.occupation.getText();
        String ff = this.PhoneNumber.getText();
        String gg = this.Email.getText();
        String hh = this.PlaceBirth.getText();
        String ii = this.Hobby.getText();
        String jj = this.Notes.getText();

        if (aa.isEmpty())
        {
            last.setText("Please enter Lastname");
        } else if (bb.isEmpty())
        {
            first.setText("Please enter Firstname");
        }
        if (cc.isEmpty())
        {
            middle.setText("Please enter MiddleName");
        } else if (dd.isEmpty())
        {
            bdate.setText("Please enter Birthdate");
        }
        if (ee.isEmpty())
        {
            Occ.setText("Please enter Occupation");
        } else if (ff.isEmpty())
        {
            number.setText("Please enter Number");
        }
        if (gg.isEmpty())
        {
            email.setText("Please enter Email Address");
        } else if (hh.isEmpty())
        {
            place.setText("Please enter Place of Birth");
        }
        if (ii.isEmpty())
        {
            hobby.setText("Please enter Hobby");
        } else if (hh.isEmpty())
        {
            note.setText("Please enter Note");
        } else
        {

            try
            {

                String sql = "insert into Core1_pr_PatientRegistration (Patient_ID,FirstName,LastName,MiddleName,PR_Gender,PR_Birthdate,address,PR_Occupation,\n"
                        + "                        PR_PhoneNo,PR_MobileNo,PR_Email,PR_BussinessPhone,PR_MaritalStatus,PR_SpouseName,PR_MaidenName,PR_Nationality,\n"
                        + "                        PR_Company,PR_Religion,PR_PlaceBirth,PR_Facebook,PR_Twitter,PR_Skype,PR_Hobby,PR_Notes,PR_Remarks,PR_Time,PR_Date,PR_Status,age) \n"
                        + "						values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                pst = conn.prepareStatement(sql);
                pst.setString(1, id.getText());
                pst.setString(2, fname.getText());
                pst.setString(3, lname.getText());
                pst.setString(4, mi.getText());
                pst.setString(5, Gender);
                pst.setString(6, ((JTextField) bday.getDateEditor().getUiComponent()).getText());
                pst.setString(7, txt_noAddress1.getText());

                pst.setString(8, occupation.getText());
                pst.setString(9, PhoneNumber.getText());
                pst.setString(10, MobileNumber.getText());
                pst.setString(11, Email.getText());
                pst.setString(12, BusinessPhone.getText());
                String value = MaritalStatus.getSelectedItem().toString();
                pst.setString(13, value);
                pst.setString(14, SpouseName.getText());
                pst.setString(15, MaidenName.getText());
                String value2 = Nationality.getSelectedItem().toString();
                pst.setString(16, value2);
                pst.setString(17, Company.getText());
                String value3 = Religion.getSelectedItem().toString();
                pst.setString(18, value3);
                pst.setString(19, PlaceBirth.getText());
                pst.setString(20, facebook.getText());
                pst.setString(21, Twitter.getText());
                pst.setString(22, Skype.getText());
                pst.setString(23, Hobby.getText());
                pst.setString(24, Notes.getText());
                pst.setString(25, remarks.getText());
                pst.setString(26, time.getText());
                pst.setString(27, date.getText());
                pst.setString(28, Active.getText());
                pst.setString(29, age.getText());

                auto_PATIENT_number();
                pst.execute();
                JOptionPane.showMessageDialog(null, "Patient successfully Registered");

                int choice1 = JOptionPane.showConfirmDialog(null, "Register another Patient?");
                if (choice1 == JOptionPane.YES_OPTION)
                {
                    lname.setText("");
                    fname.setText("");
                    mi.setText("");
                    occupation.setText("");
                    PhoneNumber.setText("");
                    MobileNumber.setText("");
                    Email.setText("");
                    BusinessPhone.setText("");
                    SpouseName.setText("");
                    MaidenName.setText("");
                    Company.setText("");
                    PlaceBirth.setText("");
                    Hobby.setText("");
                    Notes.setText("");
                    facebook.setText("");
                    Twitter.setText("");
                    Skype.setText("");

                    auto_PATIENT_number();
                    setVisible(true);
                } else
                {
                    lname.setText("");
                    fname.setText("");
                    mi.setText("");
                    occupation.setText("");
                    PhoneNumber.setText("");
                    MobileNumber.setText("");
                    Email.setText("");
                    BusinessPhone.setText("");
                    SpouseName.setText("");
                    MaidenName.setText("");
                    Company.setText("");
                    PlaceBirth.setText("");
                    Hobby.setText("");
                    Notes.setText("");
                    facebook.setText("");
                    Twitter.setText("");
                    Skype.setText("");
                    dispose();
                }

            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_sub_module_1_btnActionPerformed

    private void fnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fnameKeyTyped
    {//GEN-HEADEREND:event_fnameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (fname.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()))
        {
            evt.consume();
        } else if (fname.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar()))
        {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_fnameKeyTyped

    private void miKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_miKeyTyped
    {//GEN-HEADEREND:event_miKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (mi.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()))
        {
            evt.consume();
        } else if (mi.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar()))
        {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_miKeyTyped

    private void occupationKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_occupationKeyTyped
    {//GEN-HEADEREND:event_occupationKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (occupation.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_occupationKeyTyped

    private void lnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_lnameKeyTyped
    {//GEN-HEADEREND:event_lnameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (lname.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()))
        {
            evt.consume();
        } else if (lname.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar()))
        {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_lnameKeyTyped

    private void PhoneNumberKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_PhoneNumberKeyTyped
    {//GEN-HEADEREND:event_PhoneNumberKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {
            evt.consume();

        }
        if (PhoneNumber.getText().length() == 15)
        {
            JOptionPane.showMessageDialog(null, "Maximum Reach", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        char num = evt.getKeyChar();
        if (!Character.isDigit(num))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberKeyTyped

    private void MobileNumberKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_MobileNumberKeyTyped
    {//GEN-HEADEREND:event_MobileNumberKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {
            evt.consume();

        }
        if (MobileNumber.getText().length() == 15)
        {
            JOptionPane.showMessageDialog(null, "Maximum Reach", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        char num = evt.getKeyChar();
        if (!Character.isDigit(num))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNumberKeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        Gender = "Female";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton5ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton5ActionPerformed
        Gender = "Male";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void EmailKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_EmailKeyTyped
    {//GEN-HEADEREND:event_EmailKeyTyped
        if (Email.getText().length() == 35)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_EmailKeyTyped

    private void BusinessPhoneKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BusinessPhoneKeyTyped
    {//GEN-HEADEREND:event_BusinessPhoneKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {
            evt.consume();

        }
        if (BusinessPhone.getText().length() == 15)
        {
            JOptionPane.showMessageDialog(null, "Maximum Reach", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        char num = evt.getKeyChar();
        if (!Character.isDigit(num))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BusinessPhoneKeyTyped

    private void SpouseNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_SpouseNameKeyTyped
    {//GEN-HEADEREND:event_SpouseNameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (SpouseName.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_SpouseNameKeyTyped

    private void MaidenNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_MaidenNameKeyTyped
    {//GEN-HEADEREND:event_MaidenNameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (MaidenName.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_MaidenNameKeyTyped

    private void CompanyMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CompanyMouseReleased
    {//GEN-HEADEREND:event_CompanyMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyMouseReleased

    private void CompanyKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CompanyKeyTyped
    {//GEN-HEADEREND:event_CompanyKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (Company.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_CompanyKeyTyped

    private void PlaceBirthKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_PlaceBirthKeyTyped
    {//GEN-HEADEREND:event_PlaceBirthKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (PlaceBirth.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_PlaceBirthKeyTyped

    private void HobbyKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_HobbyKeyTyped
    {//GEN-HEADEREND:event_HobbyKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (Hobby.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_HobbyKeyTyped

    private void ContraceptionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_ContraceptionKeyTyped
    {//GEN-HEADEREND:event_ContraceptionKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {

            evt.consume();
        }

        if (Contraception.getText().length() == 20)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_ContraceptionKeyTyped

    private void facebookKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_facebookKeyTyped
    {//GEN-HEADEREND:event_facebookKeyTyped
        if (facebook.getText().length() == 35)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_facebookKeyTyped

    private void TwitterKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TwitterKeyTyped
    {//GEN-HEADEREND:event_TwitterKeyTyped
        if (Twitter.getText().length() == 35)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_TwitterKeyTyped

    private void SkypeKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_SkypeKeyTyped
    {//GEN-HEADEREND:event_SkypeKeyTyped
        if (Skype.getText().length() == 35)
        {
            JOptionPane.showMessageDialog(null, "You reach the maximum characters", null, JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_SkypeKeyTyped

    private void addpatientAncestorAdded(javax.swing.event.AncestorEvent evt)//GEN-FIRST:event_addpatientAncestorAdded
    {//GEN-HEADEREND:event_addpatientAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_addpatientAncestorAdded

    private void sub_module_1_btn6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sub_module_1_btn6MouseClicked
    {//GEN-HEADEREND:event_sub_module_1_btn6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_module_1_btn6MouseClicked

    private void sub_module_1_btn6MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sub_module_1_btn6MouseEntered
    {//GEN-HEADEREND:event_sub_module_1_btn6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_module_1_btn6MouseEntered

    private void sub_module_1_btn6MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sub_module_1_btn6MouseExited
    {//GEN-HEADEREND:event_sub_module_1_btn6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_module_1_btn6MouseExited

    private void sub_module_1_btn6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sub_module_1_btn6ActionPerformed
    {//GEN-HEADEREND:event_sub_module_1_btn6ActionPerformed
        dispose();
    }//GEN-LAST:event_sub_module_1_btn6ActionPerformed

    private void txt_noAddress1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txt_noAddress1KeyReleased
    {//GEN-HEADEREND:event_txt_noAddress1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noAddress1KeyReleased

    private void ageKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_ageKeyTyped
    {//GEN-HEADEREND:event_ageKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Active;
    private javax.swing.JTextField BusinessPhone;
    private javax.swing.JTextField Company;
    private javax.swing.JTextField Contraception;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Hobby;
    private javax.swing.JTextField MaidenName;
    private javax.swing.JComboBox<String> MaritalStatus;
    private javax.swing.JTextField MobileNumber;
    private javax.swing.JComboBox<String> Nationality;
    private javax.swing.JTextArea Notes;
    private javax.swing.JLabel Occ;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JTextField PlaceBirth;
    private javax.swing.JComboBox<String> Religion;
    private javax.swing.JTextField Skype;
    private javax.swing.JTextField SpouseName;
    private javax.swing.JTextField Twitter;
    private javax.swing.JPanel addpatient;
    private javax.swing.JTextField age;
    private javax.swing.JLabel bdate;
    private com.toedter.calendar.JDateChooser bday;
    private javax.swing.JLabel date;
    private javax.swing.JLabel email;
    private javax.swing.JLabel error11;
    private javax.swing.JLabel error4;
    private javax.swing.JTextField facebook;
    private javax.swing.JLabel first;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel hobby;
    private java.awt.Label id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JLabel last;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mi;
    private javax.swing.JLabel middle;
    private javax.swing.JLabel note;
    private javax.swing.JLabel number;
    private javax.swing.JTextField occupation;
    private javax.swing.JLabel place;
    private javax.swing.JLabel remarks;
    private javax.swing.JButton sub_module_1_btn;
    private javax.swing.JButton sub_module_1_btn6;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txt_noAddress1;
    // End of variables declaration//GEN-END:variables
private String Gender;
}
