package Module1SubModules;

import SystemInstance.MysqlConnect;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author iRHONman
 */
public class medHistory extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    CallableStatement cst = null;

    public medHistory() {
        initComponents();
        con = MysqlConnect.ConnectDB();
        tblconsultDone();

    }

    public void tblconsultDone() {

        try {
            /*   String q = "select findings_no as Consultation,name as Patient,age as Age,gender as Gender,patContact as Mobile,doctor_name as Doctor,specialization as Specialization,\n"
                    + "bp,temp,height,weight,datetime, patient_illness as Symptoms,date_sysmptoms as Since, symp_desc as Description, diagnose as Diagnose ,diag_desc as Description, date_diagnose as 'Date diagnose',\n"
                    + "medicine as Medicine,dosage as Dosage,tablet as Tablet,take as 'Take every',until as 'For',med_desc as 'Medicine description', status as Status\n"
                    + "from Core1_opd_consultationProgress where name ='" + patName.getText() + "'";*/

            String q = "select findings_no as Consultation,doctor_name as Doctor,specialization as Specialization,\n"
                    + "patient_illness as Symptoms,date_sysmptoms as Since, symp_desc as Description, diagnose as Diagnose ,diag_desc as Description, date_diagnose as 'Date diagnose',\n"
                    + "medicine as Medicine,dosage as Dosage,tablet as Tablet,take as 'Take every',until as 'For',med_desc as 'Medicine description', status as Status\n"
                    + "from Core1_opd_consultationProgress where name ='" + patName.getText() + "'";

            pst = con.prepareStatement(q);

            rs = pst.executeQuery();
            PatientTable.setModel(DbUtils.resultSetToTableModel(rs));
            /*  tbl_view1.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbl_view1.getColumnModel().getColumn(2).setPreferredWidth(15);
            tbl_view1.getColumnModel().getColumn(3).setPreferredWidth(15);
            tbl_view1.getColumnModel().getColumn(5).setPreferredWidth(15);
            tbl_view1.getColumnModel().getColumn(6).setPreferredWidth(20);*/

        } catch (Exception e) {
            System.out.println(e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Findings_pnl = new javax.swing.JPanel();
        btnAddPat = new rojerusan.RSButtonPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        gndr = new javax.swing.JLabel();
        age2 = new javax.swing.JLabel();
        age1 = new javax.swing.JLabel();
        findID = new javax.swing.JTextField();
        patID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        patName = new javax.swing.JTextField();
        Treatment = new javax.swing.JPanel();
        medType = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        medDosage = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        find_for = new javax.swing.JTextField();
        take = new javax.swing.JTextField();
        medicine = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        Diagnosis = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        find_diag = new javax.swing.JTextField();
        diag_dd = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        stat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sp = new javax.swing.JTextField();
        dr = new javax.swing.JTextField();
        Symptoms = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        find_dd = new javax.swing.JTextField();
        find_patSick = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        scrollPatient = new javax.swing.JScrollPane();
        PatientTable = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Findings_pnl.setBackground(new java.awt.Color(255, 255, 255));
        Findings_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));
        Findings_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddPat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddPatMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back36x36.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("BACK");

        javax.swing.GroupLayout btnAddPatLayout = new javax.swing.GroupLayout(btnAddPat);
        btnAddPat.setLayout(btnAddPatLayout);
        btnAddPatLayout.setHorizontalGroup(
            btnAddPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddPatLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        btnAddPatLayout.setVerticalGroup(
            btnAddPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Findings_pnl.add(btnAddPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 120, -1));

        jSeparator1.setBackground(new java.awt.Color(3, 131, 140));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        Findings_pnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1240, 10));

        jPanel8.setBackground(new java.awt.Color(240, 240, 240));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Patient Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gndr.setText("-");
        jPanel8.add(gndr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 70, -1));

        age2.setText("-");
        jPanel8.add(age2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, -1));

        age1.setText("years old,");
        jPanel8.add(age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        findID.setEditable(false);
        findID.setBackground(new java.awt.Color(255, 255, 255));
        findID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        findID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(findID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 40, -1));

        patID.setEditable(false);
        patID.setBackground(new java.awt.Color(255, 255, 255));
        patID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        patID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(patID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 40, -1));

        jLabel3.setText("Patiend ID:");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        jLabel17.setText("Patient:");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, -1));

        patName.setEditable(false);
        patName.setBackground(new java.awt.Color(255, 255, 255));
        patName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        patName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(patName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, -1));

        Findings_pnl.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 270, 110));

        Treatment.setBackground(new java.awt.Color(240, 240, 240));
        Treatment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Treatment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medType.setEditable(false);
        medType.setBackground(new java.awt.Color(255, 255, 255));
        medType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        medType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        medType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                medTypeKeyReleased(evt);
            }
        });
        Treatment.add(medType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 70, 30));

        jLabel28.setText("For");
        Treatment.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 30, 30));

        jLabel27.setText("Take every");
        Treatment.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 30));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("-");
        Treatment.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 20, 30));

        jLabel25.setText("Dosage");
        Treatment.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        medDosage.setEditable(false);
        medDosage.setBackground(new java.awt.Color(255, 255, 255));
        medDosage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        medDosage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        medDosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medDosageActionPerformed(evt);
            }
        });
        medDosage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                medDosageKeyReleased(evt);
            }
        });
        Treatment.add(medDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 90, 30));

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prescription");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Treatment.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 460, -1));

        find_for.setEditable(false);
        find_for.setBackground(new java.awt.Color(255, 255, 255));
        find_for.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        find_for.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        find_for.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                find_forKeyReleased(evt);
            }
        });
        Treatment.add(find_for, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 90, 30));

        take.setEditable(false);
        take.setBackground(new java.awt.Color(255, 255, 255));
        take.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        take.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        take.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                takeKeyReleased(evt);
            }
        });
        Treatment.add(take, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 90, 30));

        medicine.setEditable(false);
        medicine.setBackground(new java.awt.Color(255, 255, 255));
        medicine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        medicine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Treatment.add(medicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 240, 30));

        jLabel26.setText("Medicine");
        Treatment.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Medicine description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextArea3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea3KeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(jTextArea3);

        Treatment.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 430, 120));

        Findings_pnl.add(Treatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 460, 260));

        Diagnosis.setBackground(new java.awt.Color(240, 240, 240));
        Diagnosis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Diagnosis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Diagnosis Title:");
        Diagnosis.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Diagnostics");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Diagnosis.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 370, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Diagnosis description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea2KeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTextArea2);

        Diagnosis.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 120));

        jLabel34.setText("Date");
        Diagnosis.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 30));

        find_diag.setEditable(false);
        find_diag.setBackground(new java.awt.Color(255, 255, 255));
        find_diag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        find_diag.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        find_diag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                find_diagKeyReleased(evt);
            }
        });
        Diagnosis.add(find_diag, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, 30));

        diag_dd.setEditable(false);
        diag_dd.setBackground(new java.awt.Color(255, 255, 255));
        diag_dd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diag_dd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        diag_dd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diag_ddKeyReleased(evt);
            }
        });
        Diagnosis.add(diag_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, 30));

        Findings_pnl.add(Diagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 360, 260));

        jPanel7.setBackground(new java.awt.Color(240, 240, 240));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Medical doctors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Consultation status");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 110, -1));

        stat.setEditable(false);
        stat.setBackground(new java.awt.Color(255, 255, 255));
        stat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 130, -1));

        jLabel11.setText("Specialization");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, -1));

        jLabel7.setText("Doctor:");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        sp.setEditable(false);
        sp.setBackground(new java.awt.Color(255, 255, 255));
        sp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        dr.setEditable(false);
        dr.setBackground(new java.awt.Color(255, 255, 255));
        dr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 60, -1));

        Findings_pnl.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 380, 110));

        Symptoms.setBackground(new java.awt.Color(240, 240, 240));
        Symptoms.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Symptoms.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("Since:");
        Symptoms.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 30));

        find_dd.setEditable(false);
        find_dd.setBackground(new java.awt.Color(255, 255, 255));
        find_dd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        find_dd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        find_dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_ddActionPerformed(evt);
            }
        });
        Symptoms.add(find_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, 30));

        find_patSick.setEditable(false);
        find_patSick.setBackground(new java.awt.Color(255, 255, 255));
        find_patSick.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        find_patSick.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Symptoms.add(find_patSick, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 180, 30));

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Symptoms");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Symptoms.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 380, 30));

        jLabel31.setText("Symptoms Title:");
        Symptoms.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Symptoms description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        Symptoms.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 340, 130));

        Findings_pnl.add(Symptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 360, 260));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View  medical history");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        scrollPatient.setBackground(new java.awt.Color(255, 255, 255));
        scrollPatient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 112, 192), 3));

        PatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PatientTable.setAltoHead(40);
        PatientTable.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        PatientTable.setFuenteFilas(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        PatientTable.setFuenteFilasSelect(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        PatientTable.setFuenteHead(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        PatientTable.setGrosorBordeFilas(0);
        PatientTable.setGrosorBordeHead(0);
        PatientTable.setMultipleSeleccion(false);
        PatientTable.setPreferredSize(new java.awt.Dimension(300, 80));
        PatientTable.getTableHeader().setReorderingAllowed(false);
        PatientTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PatientTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        PatientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientTableMouseClicked(evt);
            }
        });
        scrollPatient.setViewportView(PatientTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Findings_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Findings_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrollPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void medTypeKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_medTypeKeyReleased
    {//GEN-HEADEREND:event_medTypeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_medTypeKeyReleased

    private void medDosageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_medDosageActionPerformed
    {//GEN-HEADEREND:event_medDosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medDosageActionPerformed

    private void medDosageKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_medDosageKeyReleased
    {//GEN-HEADEREND:event_medDosageKeyReleased

    }//GEN-LAST:event_medDosageKeyReleased

    private void find_forKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_find_forKeyReleased
    {//GEN-HEADEREND:event_find_forKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_find_forKeyReleased

    private void takeKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_takeKeyReleased
    {//GEN-HEADEREND:event_takeKeyReleased

    }//GEN-LAST:event_takeKeyReleased

    private void jTextArea3AncestorAdded(javax.swing.event.AncestorEvent evt)//GEN-FIRST:event_jTextArea3AncestorAdded
    {//GEN-HEADEREND:event_jTextArea3AncestorAdded
        jTextArea3.setLineWrap(true);
        jTextArea3.setWrapStyleWord(true);
    }//GEN-LAST:event_jTextArea3AncestorAdded

    private void jTextArea3KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea3KeyReleased
    {//GEN-HEADEREND:event_jTextArea3KeyReleased

    }//GEN-LAST:event_jTextArea3KeyReleased

    private void jTextArea2AncestorAdded(javax.swing.event.AncestorEvent evt)//GEN-FIRST:event_jTextArea2AncestorAdded
    {//GEN-HEADEREND:event_jTextArea2AncestorAdded
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
    }//GEN-LAST:event_jTextArea2AncestorAdded

    private void jTextArea2KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea2KeyReleased
    {//GEN-HEADEREND:event_jTextArea2KeyReleased

    }//GEN-LAST:event_jTextArea2KeyReleased

    private void find_diagKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_find_diagKeyReleased
    {//GEN-HEADEREND:event_find_diagKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_find_diagKeyReleased

    private void diag_ddKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_diag_ddKeyReleased
    {//GEN-HEADEREND:event_diag_ddKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_diag_ddKeyReleased

    private void find_ddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_find_ddActionPerformed
    {//GEN-HEADEREND:event_find_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_find_ddActionPerformed

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt)//GEN-FIRST:event_jTextArea1AncestorAdded
    {//GEN-HEADEREND:event_jTextArea1AncestorAdded
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea1KeyReleased
    {//GEN-HEADEREND:event_jTextArea1KeyReleased

    }//GEN-LAST:event_jTextArea1KeyReleased

    private void btnAddPatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPatMousePressed

        this.dispose();
    }//GEN-LAST:event_btnAddPatMousePressed

    private void PatientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientTableMouseClicked
        /*  int row = tblPatient.rowAtPoint(evt.getPoint());
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) == InputEvent.BUTTON3_MASK) {
            this.tblPatient.setRowSelectionInterval(row, row);
            MousePos = evt.getY() / 16;
            menuC.show(evt.getComponent(), evt.getX(), evt.getY());
        } else {
            this.tblPatient.setRowSelectionInterval(row, row);
        }*/
        try {
            int row = PatientTable.getSelectedRow();
            String Table_transfer = (PatientTable.getModel().getValueAt(row, 0).toString());
            /* String sql = "select findings_no as Consultation,name as Patient,age as Age,gender as Gender,patContact as Mobile,doctor_name as Doctor,specialization as Specialization,\n"
                    + "bp,temp,height,weight,datetime, patient_illness as Symptoms,date_sysmptoms as Since, symp_desc as Description, diagnose as Diagnose ,diag_desc as Description, date_diagnose as 'Date diagnose',\n"
                    + "medicine as Medicine,dosage as Dosage,tablet as Tablet,take as 'Take every',until as 'For',med_desc as 'Medicine description', status as Status\n"
                    + "from Core1_opd_consultationProgress where findings_no='" + Table_transfer + "' ";*/
            String sql = "select findings_no as Consultation,doctor_name as Doctor,specialization as Specialization,\n"
                    + "patient_illness as Symptoms,date_sysmptoms as Since, symp_desc as Description, diagnose as Diagnose ,diag_desc as Description, date_diagnose as 'Date diagnose',\n"
                    + "medicine as Medicine,dosage as Dosage,tablet as Tablet,take as 'Take every',until as 'For',med_desc as 'Medicine description', status as Status\n"
                    + "from Core1_opd_consultationProgress where findings_no='" + Table_transfer + "' ";
            
            
            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                String add00 = rs.getString("Consultation");
                findID.setText(add00);
//                String add11 = rs.getString("Patient");
//                find_patSick.setText(add11);
//                String add12 = rs.getString("Age");
//                find_dd.setText(add12);
//                String add23 = rs.getString("Gender");
//                jTextArea1.setText(add23);
//                String add33 = rs.getString("Mobile");
//                find_diag.setText(add33);
                String add44 = rs.getString("Doctor");
                dr.setText(add44);
                String add55 = rs.getString("Specialization");
                sp.setText(add55);
//                String add66 = rs.getString("bp");
//                medicine.setText(add66);
//                String add77 = rs.getString("temp");
//                medDosage.setText(add77);
//                String add88 = rs.getString("height");
//                medType.setText(add88);
//                String add99 = rs.getString("weight");
//                take.setText(add99);
//                String add101 = rs.getString("datetime");
//                find_for.setText(add101);

                String add0 = rs.getString("Symptoms");
                find_patSick.setText(add0);
                String add1 = rs.getString("Since");
                find_dd.setText(add1);
                String add2 = rs.getString("Description");
                jTextArea1.setText(add2);
                String add3 = rs.getString("Diagnose");
                find_diag.setText(add3);
                String add4 = rs.getString("Date diagnose");
                diag_dd.setText(add4);
                String add5 = rs.getString("Description");
                jTextArea2.setText(add5);
                String add6 = rs.getString("Medicine");
                medicine.setText(add6);
                String add7 = rs.getString("Dosage");
                medDosage.setText(add7);
                String add8 = rs.getString("Tablet");
                medType.setText(add8);
                String add9 = rs.getString("Take every");
                take.setText(add9);
                String add10 = rs.getString("For");
                find_for.setText(add10);
                String add1111 = rs.getString("Medicine description");
                jTextArea3.setText(add1111);
                String add11121 = rs.getString("Status");
                stat.setText(add11121);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_PatientTableMouseClicked

    private void PatientTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PatientTableAncestorAdded

        tblconsultDone();
    }//GEN-LAST:event_PatientTableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Diagnosis;
    private javax.swing.JPanel Findings_pnl;
    public static rojerusan.RSTableMetro PatientTable;
    private javax.swing.JPanel Symptoms;
    private javax.swing.JPanel Treatment;
    private javax.swing.JLabel age1;
    public static javax.swing.JLabel age2;
    private rojerusan.RSButtonPane btnAddPat;
    public static javax.swing.JTextField diag_dd;
    public static javax.swing.JTextField dr;
    public static javax.swing.JTextField findID;
    public static javax.swing.JTextField find_dd;
    public static javax.swing.JTextField find_diag;
    public static javax.swing.JTextField find_for;
    public static javax.swing.JTextField find_patSick;
    public static javax.swing.JLabel gndr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    public static javax.swing.JTextArea jTextArea3;
    public static javax.swing.JTextField medDosage;
    public static javax.swing.JTextField medType;
    public static javax.swing.JTextField medicine;
    public static javax.swing.JTextField patID;
    public static javax.swing.JTextField patName;
    public static javax.swing.JScrollPane scrollPatient;
    public static javax.swing.JTextField sp;
    public static javax.swing.JTextField stat;
    public static javax.swing.JTextField take;
    // End of variables declaration//GEN-END:variables
}
