package Module1SubModules;

import AlertsCore1.AWTUtilities;
import Notifications.DesktopNotify;
import SystemInstance.MysqlConnect;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class printID extends javax.swing.JFrame {

    public String imgPath = null;
    DefaultListModel model;
    int enter = 0;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stmt = null;
    private static int CHAR_DELTA = 1000;
    private String m_key;
    private long m_time;
    private int MousePos;

    public printID() {
        initComponents();
        conn = MysqlConnect.ConnectDB();
        issued.setDateFormatString("MMM dd, yyyy");
        select_pattient();
        AutoCompleteDecorator.decorate(cbFilter);
        //    jList2.setVisible(false);
        AWTUtilities.setOpaque(this, false);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0, 0, screenSize.width, screenSize.height);

        //Search bar
        model = new DefaultListModel();
    }

    private void select_pattient() {
        try {
            String sql = "select  Patient_ID from Core1_pr_PatientRegistration  order by Patient_ID ";
            // String sql = "select id from Core1_pr_Pat_img";
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                cbFilter.addItem(rs.getString("Patient_ID"));
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelImage1 = new rojerusan.RSPanelImage();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtuser4 = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        txtuser3 = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        txtuser2 = new app.bolivia.swing.JCTextField();
        txtuser1 = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtuser = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        bod1 = new app.bolivia.swing.JCTextField();
        fillAll1 = new rojerusan.RSMaterialButtonRound();
        btnAddPat = new rojerusan.RSButtonPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        asterisk9 = new javax.swing.JLabel();
        issued = new com.toedter.calendar.JDateChooser();
        bod = new app.bolivia.swing.JCTextField();
        adds = new rojerusan.RSMetroTextFullPlaceHolder();
        newG1 = new rojerusan.RSButtonHover();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbFilter = new rojerusan.RSComboMetro();
        jLabel4 = new javax.swing.JLabel();
        cerrar = new principal.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Images/transparent.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel4.setBorder(dropShadowBorder1);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(" from the date it was issued. ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 260, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("This I'd will be valid (1) one year");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 260, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bday40x40.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pat.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 40, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Photo");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 150, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(58, 159, 171));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        jLabel1.setEnabled(false);
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 40, 40));

        txtuser4.setEditable(false);
        txtuser4.setBackground(new java.awt.Color(255, 255, 255));
        txtuser4.setBorder(null);
        txtuser4.setForeground(new java.awt.Color(58, 159, 171));
        txtuser4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser4.setPlaceholder("MOBILE NUMBER");
        txtuser4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser4KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 230, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cno_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 310, 50));

        txtuser3.setEditable(false);
        txtuser3.setBackground(new java.awt.Color(255, 255, 255));
        txtuser3.setBorder(null);
        txtuser3.setForeground(new java.awt.Color(58, 159, 171));
        txtuser3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser3.setPlaceholder("REGISTRATION DATE");
        txtuser3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser3KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 230, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/work_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 50));

        txtuser2.setEditable(false);
        txtuser2.setBackground(new java.awt.Color(255, 255, 255));
        txtuser2.setBorder(null);
        txtuser2.setForeground(new java.awt.Color(58, 159, 171));
        txtuser2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser2.setPlaceholder("Middle name");
        txtuser2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser2KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 230, 30));

        txtuser1.setEditable(false);
        txtuser1.setBackground(new java.awt.Color(255, 255, 255));
        txtuser1.setBorder(null);
        txtuser1.setForeground(new java.awt.Color(58, 159, 171));
        txtuser1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser1.setPlaceholder("Last name");
        txtuser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuser1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser1KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 230, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pat_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pat_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 310, 50));

        txtuser.setEditable(false);
        txtuser.setBackground(new java.awt.Color(255, 255, 255));
        txtuser.setBorder(null);
        txtuser.setForeground(new java.awt.Color(58, 159, 171));
        txtuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser.setPlaceholder("First name");
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuserKeyTyped(evt);
            }
        });
        jPanel4.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 230, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pat_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 50));

        bod1.setBorder(null);
        bod1.setForeground(new java.awt.Color(58, 159, 171));
        bod1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bod1.setPlaceholder("Patient ID");
        bod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bod1ActionPerformed(evt);
            }
        });
        jPanel4.add(bod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 80, 20));

        fillAll1.setText("PRINT");
        fillAll1.setFont(new java.awt.Font("Roboto Medium", 1, 13)); // NOI18N
        fillAll1.setMaximumSize(new java.awt.Dimension(82, 26));
        fillAll1.setMinimumSize(new java.awt.Dimension(82, 26));
        fillAll1.setPreferredSize(new java.awt.Dimension(88, 28));
        fillAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillAll1ActionPerformed(evt);
            }
        });
        jPanel4.add(fillAll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 190, 50));

        btnAddPat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddPatMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/browse36x36.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Browse");

        javax.swing.GroupLayout btnAddPatLayout = new javax.swing.GroupLayout(btnAddPat);
        btnAddPat.setLayout(btnAddPatLayout);
        btnAddPatLayout.setHorizontalGroup(
            btnAddPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddPatLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addGap(0, 0, 0)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );
        btnAddPatLayout.setVerticalGroup(
            btnAddPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(btnAddPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 110, -1));

        asterisk9.setBackground(new java.awt.Color(255, 255, 255));
        asterisk9.setFont(new java.awt.Font("Arial", 3, 9)); // NOI18N
        asterisk9.setForeground(new java.awt.Color(204, 0, 0));
        jPanel4.add(asterisk9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 200, 40));

        issued.setBackground(new java.awt.Color(1, 113, 124));
        issued.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 113, 124), 2));
        issued.setPreferredSize(new java.awt.Dimension(250, 42));
        issued.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                issuedAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        issued.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                issuedMousePressed(evt);
            }
        });
        jPanel4.add(issued, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 200, 40));

        bod.setEditable(false);
        bod.setBackground(new java.awt.Color(255, 255, 255));
        bod.setBorder(null);
        bod.setForeground(new java.awt.Color(58, 159, 171));
        bod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bod.setPlaceholder("Valid until");
        bod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodActionPerformed(evt);
            }
        });
        jPanel4.add(bod, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 110, 20));

        adds.setEditable(false);
        adds.setBackground(new java.awt.Color(255, 255, 255));
        adds.setForeground(new java.awt.Color(1, 113, 124));
        adds.setBorderColor(new java.awt.Color(255, 255, 255));
        adds.setBotonColor(new java.awt.Color(1, 113, 124));
        adds.setMayusculas(true);
        adds.setPhColor(new java.awt.Color(0, 0, 0));
        adds.setPlaceholder("Address");
        jPanel4.add(adds, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 190, -1));

        newG1.setBackground(new java.awt.Color(255, 255, 255));
        newG1.setBorder(null);
        newG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adds40x40.png"))); // NOI18N
        jPanel4.add(newG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 47, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 820, 380));

        jPanel3.setBackground(new java.awt.Color(0, 112, 192));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 860, 150));

        jPanel2.setBackground(new java.awt.Color(0, 112, 192));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Printing Patient ID");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 14, 258, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/old1.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 11, -1, 42));

        cbFilter.setEditable(true);
        cbFilter.setMaximumRowCount(4);
        cbFilter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Click here" }));
        cbFilter.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cbFilter.setPreferredSize(new java.awt.Dimension(188, 30));
        cbFilter.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbFilterPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel2.add(cbFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 12, 119, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search Patient:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 11, -1, 30));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 159, 171), 2));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Exit</h4> </body> </html>");
        cerrar.setAlignmentX(5.0F);
        cerrar.setAlignmentY(1.0F);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtuser4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser4KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtuser4KeyTyped

    private void txtuser3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser3KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
            evt.consume();
        } else if (txtuser3.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtuser3KeyTyped

    private void txtuser2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser2KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
            evt.consume();
        } else if (txtuser2.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtuser2KeyTyped

    private void txtuser1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuser1KeyReleased

    private void txtuser1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
            evt.consume();
        } else if (txtuser1.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtuser1KeyTyped

    private void txtuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
            evt.consume();
        } else if (txtuser.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtuserKeyTyped

    private void bod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bod1ActionPerformed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MousePressed

    private void btnAddPatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPatMousePressed

        JFileChooser chooser = new JFileChooser("c:\\Documents");

        LookAndFeel previousLF = UIManager.getLookAndFeel();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            chooser = new JFileChooser();
            UIManager.setLookAndFeel(previousLF);
        } catch (IllegalAccessException | UnsupportedLookAndFeelException | InstantiationException | ClassNotFoundException e) {
        }
        //Add whatever other settings you want to the method
        // chooser.showOpenDialog(frame);

        chooser.setDialogTitle("Choose Photo");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        chooser.addChoosableFileFilter(fnef);
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {

            File fs = chooser.getSelectedFile();
            String path = fs.getAbsolutePath();
            imgPath = path;
            ImageIcon icon = new ImageIcon(path);

            Image img = icon.getImage();
            Image newImg = img.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newImc = new ImageIcon(newImg);
            jLabel2.setIcon(newImc);

        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No Images Selected");

        }
    }//GEN-LAST:event_btnAddPatMousePressed

    private void cbFilterPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbFilterPopupMenuWillBecomeInvisible

        String diagnose = (String) cbFilter.getSelectedItem();
        //       String sql = "select diagnose_description,medicine,dosage,medicine_type,take,medicine_description"
        //               + "from  Core1_opd_treatmentmedicine where title = ?";

        // String sql = "select LastName,FirstName,MiddleName,Patient_ID,PR_Date,PR_Birthdate,image from Core1_pr_PatientRegistration where Patient_ID = ? ";
        String sql = "select LastName,FirstName,MiddleName,Patient_ID,PR_Date,PR_Birthdate,image,address from Core1_pr_PatientRegistration where Patient_ID = ? ";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, diagnose);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("LastName");
                txtuser1.setText(add1);
                String add2 = rs.getString("FirstName");
                txtuser.setText(add2);
                String add22 = rs.getString("MiddleName");
                txtuser2.setText(add22);
                String add4 = rs.getString("Patient_ID");
                jLabel1.setText(add4);
                String add7 = rs.getString("PR_Birthdate");
                txtuser4.setText(add7);
                String add8 = rs.getString("PR_Date");
                txtuser3.setText(add8);
                String add9 = rs.getString("address");
                adds.setText(add9);
                byte[] img2 = rs.getBytes("image");
                ImageIcon img3 = new ImageIcon(img2);
                Image img = img3.getImage();
                Image newImg = img.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImc = new ImageIcon(newImg);
                jLabel2.setIcon(newImc);

            }

        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err);
        }
    }//GEN-LAST:event_cbFilterPopupMenuWillBecomeInvisible

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void fillAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillAll1ActionPerformed
 
     if (((JTextField) issued.getDateEditor().getUiComponent()).getText().isEmpty()) {
            // Validation message. 
            DesktopNotify.showDesktopMessage("INPUT MISSING...", "Please select date ID expired of patient " + txtuser.getText()+" "+txtuser1.getText(),
                    DesktopNotify.INPUT_REQUEST, 8000);
            asterisk9.setBorder(BorderFactory.createLineBorder(Color.red));
            asterisk9.setVisible(true);
        }else{
         try {
            String query22 = "update Core1_pr_PatientRegistration set  PR_Date_Issued = ?  where Patient_ID='" + jLabel1.getText() + "' ";

            PreparedStatement ps = conn.prepareStatement(query22);

            ps.setString(1, ((JTextField) issued.getDateEditor().getUiComponent()).getText());
            ps.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            //path of .jrxml
            InputStream in = new FileInputStream(new File("C:\\Users\\iRHONman\\Desktop\\PS1\\Template\\undone\\src\\Module1SubModules\\printIDF.jrxml"));
            //     InputStream in = new FileInputStream(new File("C:\\Users\\iRHONman\\Desktop\\PS1\\Template\\HMSTemplate(Final)\\src"
            //           + "\\Module1SubModules\\raffy.jrxml"));
            JasperDesign jd = JRXmlLoader.load(in);
            String sql = "select LastName,FirstName,MiddleName,Patient_ID,PR_Date,PR_Birthdate,image,PR_Date_Issued,address from Core1_pr_PatientRegistration "
                    + "where Patient_ID= '" + jLabel1.getText() + "' ";
            //  String sql = "select LastName,FirstName from Core1_pr_PatientRegistration";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            HashMap para = new HashMap();
            JasperPrint j = JasperFillManager.fillReport(jr, para, conn);
            JasperViewer.viewReport(j, false);
            //   OutputStream os = new FileOutputStream(new File("D:\\reports"));
            // JasperExportManager.exportReportToPdfStream(j, os);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
     }
        
    }//GEN-LAST:event_fillAll1ActionPerformed

    private void issuedAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_issuedAncestorAdded

        //    d.setText("Todaydate"+((JTextField) bday.getDateEditor().getUiComponent()).getText());

    }//GEN-LAST:event_issuedAncestorAdded

    private void issuedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuedMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_issuedMousePressed

    private void bodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMetroTextFullPlaceHolder adds;
    private javax.swing.JLabel asterisk9;
    public static app.bolivia.swing.JCTextField bod;
    public static app.bolivia.swing.JCTextField bod1;
    private rojerusan.RSButtonPane btnAddPat;
    private rojerusan.RSComboMetro cbFilter;
    private principal.MaterialButton cerrar;
    private rojerusan.RSMaterialButtonRound fillAll1;
    private com.toedter.calendar.JDateChooser issued;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private rojerusan.RSButtonHover newG1;
    private rojerusan.RSPanelImage rSPanelImage1;
    public static javax.swing.JLabel titulo;
    public static app.bolivia.swing.JCTextField txtuser;
    public static app.bolivia.swing.JCTextField txtuser1;
    public static app.bolivia.swing.JCTextField txtuser2;
    public static app.bolivia.swing.JCTextField txtuser3;
    public static app.bolivia.swing.JCTextField txtuser4;
    // End of variables declaration//GEN-END:variables
}
