package Module1SubModules;

import AlertsCore1.AWTUtilities;
import SystemInstance.MysqlConnect;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AbstractDocument;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class UpdateINFO extends javax.swing.JFrame {

    public String imgPath = null;
    DefaultListModel model;
    int enter = 0;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stmt = null;
    private static int CHAR_DELTA = 1000;
    private String m_key;
    private long m_time;
    private int MousePos;

    public UpdateINFO() {
        initComponents();
        conn = MysqlConnect.ConnectDB();
        select_pattient();
        Limit();
        AutoCompleteDecorator.decorate(cbFilter);
        //    jList2.setVisible(false);
        AWTUtilities.setOpaque(this, false);

        //Search bar
        model = new DefaultListModel();
    }

    public void Limit() {
// limit of per textfield
        ((AbstractDocument) txtuser5.getDocument()).setDocumentFilter(new SystemInstance.LimitText(7));
        ((AbstractDocument) txtuser4.getDocument()).setDocumentFilter(new SystemInstance.LimitText(10));

    }

    private void select_pattient() {
        try {
            String sql = "select  Patient_ID from Core1_pr_PatientRegistration  order by Patient_ID ";
            //String sql = "select App_ID from SignUp";
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                cbFilter.addItem(rs.getString("Patient_ID"));
            }

        } catch (Exception e) {
        }
    }

    private void select_pat() {
        try {
            String sql = "select martial_status from Martial_Status_tbl";
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                MaritalStatus.addItem(rs.getString("martial_status"));
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jPanel4 = new javax.swing.JPanel();
        txtuser6 = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtuser5 = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        txtuser4 = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        txtuser3 = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        txtuser2 = new app.bolivia.swing.JCTextField();
        txtuser1 = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtuser = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bod1 = new app.bolivia.swing.JCTextField();
        adds = new app.bolivia.swing.JCTextField();
        fillAll = new rojerusan.RSMaterialButtonRound();
        btnAddPat = new rojerusan.RSButtonPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        exCP = new javax.swing.JLabel();
        exCP1 = new javax.swing.JLabel();
        MaritalStatus = new rojerusan.RSComboMetro();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbFilter = new rojerusan.RSComboMetro();
        jLabel4 = new javax.swing.JLabel();
        cerrar = new principal.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.png"))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel4.setBorder(dropShadowBorder1);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtuser6.setBorder(null);
        txtuser6.setForeground(new java.awt.Color(58, 159, 171));
        txtuser6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser6.setPlaceholder("Civil status");
        txtuser6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuser6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser6KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 160, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pat.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 40, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Photo");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 150, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(58, 159, 171));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adds40x40.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/martial40x40.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 40, 40));

        txtuser5.setBorder(null);
        txtuser5.setForeground(new java.awt.Color(58, 159, 171));
        txtuser5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser5.setPlaceholder("Phone number");
        txtuser5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser5KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 230, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pob_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 310, 50));

        txtuser4.setBorder(null);
        txtuser4.setForeground(new java.awt.Color(58, 159, 171));
        txtuser4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser4.setPlaceholder("Mobile number");
        txtuser4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser4KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 230, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cno_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 310, 50));

        txtuser3.setBorder(null);
        txtuser3.setForeground(new java.awt.Color(58, 159, 171));
        txtuser3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser3.setPlaceholder("Occupation");
        txtuser3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser3KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 230, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/work_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 310, 50));

        txtuser2.setBorder(null);
        txtuser2.setForeground(new java.awt.Color(58, 159, 171));
        txtuser2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser2.setPlaceholder("Middle name");
        txtuser2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser2KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 230, 30));

        txtuser1.setBorder(null);
        txtuser1.setForeground(new java.awt.Color(58, 159, 171));
        txtuser1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser1.setPlaceholder("Last name");
        txtuser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuser1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser1KeyTyped(evt);
            }
        });
        jPanel4.add(txtuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 230, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pat_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pat_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 50));

        txtuser.setBorder(null);
        txtuser.setForeground(new java.awt.Color(58, 159, 171));
        txtuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuser.setPlaceholder("First name");
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuserKeyTyped(evt);
            }
        });
        jPanel4.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 230, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pat_txtfield.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(58, 159, 171));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 200, 80));

        bod1.setBorder(null);
        bod1.setForeground(new java.awt.Color(58, 159, 171));
        bod1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bod1.setPlaceholder("Patient ID");
        bod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bod1ActionPerformed(evt);
            }
        });
        jPanel4.add(bod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 80, 20));

        adds.setBorder(null);
        adds.setForeground(new java.awt.Color(58, 159, 171));
        adds.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adds.setPlaceholder("Address");
        adds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsActionPerformed(evt);
            }
        });
        jPanel4.add(adds, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 110, 20));

        fillAll.setText("Update Information");
        fillAll.setFont(new java.awt.Font("Roboto Medium", 1, 13)); // NOI18N
        fillAll.setMaximumSize(new java.awt.Dimension(82, 26));
        fillAll.setMinimumSize(new java.awt.Dimension(82, 26));
        fillAll.setPreferredSize(new java.awt.Dimension(88, 28));
        fillAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillAllActionPerformed(evt);
            }
        });
        jPanel4.add(fillAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 190, 40));

        btnAddPat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddPatMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/browse36x36.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Browse");

        javax.swing.GroupLayout btnAddPatLayout = new javax.swing.GroupLayout(btnAddPat);
        btnAddPat.setLayout(btnAddPatLayout);
        btnAddPatLayout.setHorizontalGroup(
            btnAddPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddPatLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addGap(0, 0, 0)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );
        btnAddPatLayout.setVerticalGroup(
            btnAddPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(btnAddPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 110, -1));

        exCP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exCP.setForeground(new java.awt.Color(255, 0, 0));
        exCP.setText("(e.g., 9123456789)");
        jPanel4.add(exCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 110, -1));

        exCP1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exCP1.setForeground(new java.awt.Color(255, 0, 0));
        exCP1.setText("(e.g., 9359117)");
        jPanel4.add(exCP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 90, -1));

        MaritalStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Civil Status", "Single", "Married", "Widdowed", "Separated", "Divorce" }));
        MaritalStatus.setColorArrow(new java.awt.Color(0, 204, 204));
        MaritalStatus.setColorBorde(new java.awt.Color(0, 153, 153));
        MaritalStatus.setColorFondo(new java.awt.Color(1, 113, 124));
        MaritalStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(MaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 160, 40));

        panel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 820, 380));

        jPanel3.setBackground(new java.awt.Color(0, 112, 192));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 390, 860, 150));

        jPanel2.setBackground(new java.awt.Color(0, 112, 192));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Update Patient Information");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 14, 258, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/old1.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 11, -1, 42));

        cbFilter.setEditable(true);
        cbFilter.setMaximumRowCount(4);
        cbFilter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Click here" }));
        cbFilter.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cbFilter.setPreferredSize(new java.awt.Dimension(188, 30));
        cbFilter.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbFilterPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel2.add(cbFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 12, 119, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search Patient:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 11, -1, 30));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 159, 171), 2));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Exit</h4> </body> </html>");
        cerrar.setAlignmentX(5.0F);
        cerrar.setAlignmentY(1.0F);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, 40, 40));

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 860, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtuser6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuser6KeyReleased

    private void txtuser6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuser6KeyTyped

    private void txtuser5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser5KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        String a = this.txtuser5.getText();
        if (a.isEmpty()) {
            exCP1.setVisible(true);
        } else {
            exCP1.setVisible(false);
        }
    }//GEN-LAST:event_txtuser5KeyTyped

    private void txtuser4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser4KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        String a = this.txtuser4.getText();
        if (a.isEmpty()) {
            exCP.setVisible(true);
        } else {
            exCP.setVisible(false);
        }
    }//GEN-LAST:event_txtuser4KeyTyped

    private void txtuser3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser3KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
            evt.consume();
        } else if (txtuser3.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtuser3KeyTyped

    private void txtuser2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser2KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
            evt.consume();
        } else if (txtuser2.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtuser2KeyTyped

    private void txtuser1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuser1KeyReleased

    private void txtuser1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
            evt.consume();
        } else if (txtuser1.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtuser1KeyTyped

    private void txtuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
            evt.consume();
        } else if (txtuser.getText().trim().length() == 0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtuserKeyTyped

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void bod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bod1ActionPerformed

    private void addsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addsActionPerformed

    private void fillAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillAllActionPerformed

        try {

            String query2 = "update Core1_pr_PatientRegistration set FirstName = '" + txtuser.getText() + "', LastName = '" + txtuser1.getText() + "',"
                    + "MiddleName = '" + txtuser2.getText() + "',PR_Occupation = '" + txtuser3.getText() + "',PR_MobileNo = '" + txtuser4.getText() + "',"
                    + "PR_PhoneNo = '" + txtuser5.getText() + "',PR_MaritalStatus = '" + MaritalStatus.getSelectedItem().toString() + "',address = '" + jTextArea1.getText() + "' "
                    + " where Patient_ID='" + jLabel1.getText() + "' ";

            java.sql.Statement st = null;
            st = conn.createStatement();
            st.executeUpdate(query2);

            try {
                InputStream img2 = new FileInputStream(new File(imgPath));
                String query22 = "update Core1_pr_PatientRegistration set  image = ?  where Patient_ID='" + jLabel1.getText() + "' ";

                PreparedStatement ps = conn.prepareStatement(query22);

                ps.setBlob(1, img2);

                ps.executeUpdate();
            } catch (Exception e) {

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        JOptionPane.showMessageDialog(null, "Patient Successfully update information");
        cbFilter.setSelectedIndex(0);
        txtuser.setText("");
        txtuser1.setText("");
        txtuser2.setText("");
        txtuser3.setText("");
        txtuser4.setText("");
        txtuser5.setText("");
        jLabel1.setText("");
        txtuser6.setText("");
        MaritalStatus.setSelectedIndex(0);
        jTextArea1.setText("");
        jLabel2.setText("Photo");
    }//GEN-LAST:event_fillAllActionPerformed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MousePressed

    private void btnAddPatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPatMousePressed

        JFileChooser chooser = new JFileChooser("c:\\Documents");

        LookAndFeel previousLF = UIManager.getLookAndFeel();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            chooser = new JFileChooser();
            UIManager.setLookAndFeel(previousLF);
        } catch (IllegalAccessException | UnsupportedLookAndFeelException | InstantiationException | ClassNotFoundException e) {
        }
        //Add whatever other settings you want to the method
        // chooser.showOpenDialog(frame);

        chooser.setDialogTitle("Choose Photo");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        chooser.addChoosableFileFilter(fnef);
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {

            File fs = chooser.getSelectedFile();
            String path = fs.getAbsolutePath();
            imgPath = path;
            ImageIcon icon = new ImageIcon(path);

            Image img = icon.getImage();
            Image newImg = img.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newImc = new ImageIcon(newImg);
            jLabel2.setIcon(newImc);

        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No Images Selected");

        }
    }//GEN-LAST:event_btnAddPatMousePressed

    private void cbFilterPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbFilterPopupMenuWillBecomeInvisible

        String diagnose = (String) cbFilter.getSelectedItem();

        String sql = "select  Patient_ID,PR_MaritalStatus,\n"
                + "LastName,FirstName,MiddleName,address,PR_MobileNo,PR_PhoneNo,PR_Occupation,image\n"
                + " from  Core1_pr_PatientRegistration where Patient_ID = ? ";

        //   String sql = "select App_ID from SignUp ";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, diagnose);
            rs = pst.executeQuery();
            if (rs.next()) {
                // String add1 = rs.getString("App_ID");
                // jLabel1.setText(add1);
                String add1 = rs.getString("Patient_ID");
                jLabel1.setText(add1);
                String add11 = rs.getString("LastName");
                txtuser1.setText(add11);
                String add2 = rs.getString("FirstName");
                txtuser.setText(add2);
                String add22 = rs.getString("MiddleName");
                txtuser2.setText(add22);
                String add3 = rs.getString("address");
                jTextArea1.setText(add3);
                String add4 = rs.getString("PR_MobileNo");
                txtuser4.setText(add4);
                String add44 = rs.getString("PR_PhoneNo");
                txtuser5.setText(add44);
                String add7 = rs.getString("Patient_ID");
                jLabel1.setText(add7);
                String add8 = rs.getString("PR_Occupation");
                txtuser3.setText(add8);
                String add12 = rs.getString("PR_MaritalStatus");
                txtuser6.setText(add12);
                byte[] img2 = rs.getBytes("image");
                ImageIcon img3 = new ImageIcon(img2);
                Image img = img3.getImage();
                Image newImg = img.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImc = new ImageIcon(newImg);
                jLabel2.setIcon(newImc);

            }

        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err);
        }
    }//GEN-LAST:event_cbFilterPopupMenuWillBecomeInvisible

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateINFO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSComboMetro MaritalStatus;
    public static app.bolivia.swing.JCTextField adds;
    public static app.bolivia.swing.JCTextField bod1;
    private rojerusan.RSButtonPane btnAddPat;
    private rojerusan.RSComboMetro cbFilter;
    private principal.MaterialButton cerrar;
    private javax.swing.JLabel exCP;
    private javax.swing.JLabel exCP1;
    private rojerusan.RSMaterialButtonRound fillAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private org.edisoncor.gui.panel.Panel panel1;
    public static javax.swing.JLabel titulo;
    public static app.bolivia.swing.JCTextField txtuser;
    public static app.bolivia.swing.JCTextField txtuser1;
    public static app.bolivia.swing.JCTextField txtuser2;
    public static app.bolivia.swing.JCTextField txtuser3;
    public static app.bolivia.swing.JCTextField txtuser4;
    public static app.bolivia.swing.JCTextField txtuser5;
    public static app.bolivia.swing.JCTextField txtuser6;
    // End of variables declaration//GEN-END:variables
}
