/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module1SubModules;

import SystemInstance.MysqlConnect;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.Dimension;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ivy tromata
 */
public class Webb extends javax.swing.JFrame {
Webcam webcam;
Boolean isRunning = false;
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null; 
    /**
     * Creates new form Webb
     */
    public Webb() {
        initComponents();
        conn = MysqlConnect.ConnectDB();
        webcam = Webcam.getDefault();
        webcam.setViewSize(new Dimension(320, 240));
        webcam.open();
Patient();
    }
private void Patient(){
    
        try{
           
           String sql = "Select Patient_ID as ID,concat(LastName,', ',FirstName,' ',MiddleName) as Name FROM Core1_pr_PatientRegistration";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageHolder = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        attach_image = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        lname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fname = new javax.swing.JTextField();
        mi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageHolder.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(imageHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 320, 240));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CAPTURE");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 120, 30));

        attach_image.setText("ATTACH IMAGE");
        attach_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attach_imageActionPerformed(evt);
            }
        });
        getContentPane().add(attach_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 120, 30));
        getContentPane().add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 300, 40));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 250, 240));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 160, 30));

        jButton1.setText("saveeee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 160, 30));
        getContentPane().add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 160, 30));

        jLabel1.setText("fname");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 60, 30));

        jLabel2.setText("mi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 60, 30));

        jLabel3.setText("lname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 60, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            if(!isRunning)
            {
                isRunning = true;
             new VideoFeedTaker().start();
              
            }
            else{
                isRunning = false;
                Webcam webcam = Webcam.getDefault();
                webcam.open();
                try {
                    ImageIO.write(webcam.getImage(), "JPG", new File("Patient.jpg"));
                } catch (IOException ex) {
                    Logger.getLogger(Webb.class.getName()).log(Level.SEVERE, null, ex);
                }
            }                   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void attach_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attach_imageActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        path.setText(filename);

        try{
            File image =new File (filename);
            FileInputStream fis= new FileInputStream(image);

            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){
                bos.write(buf,0,readNum);

            }
            person_image=bos.toByteArray();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);;
        }

    }//GEN-LAST:event_attach_imageActionPerformed

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
Patient();        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblAncestorAdded

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row =tbl.getSelectedRow();
        String Table_click=(tbl.getModel().getValueAt(row,0).toString());
        try{
            String sql="SELECT * from Core1_pr_PatientRegistration where Patien_ID='"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if (rs.next()) {
                byte[]imagedata =rs.getBytes("image");
                format =new ImageIcon(imagedata);
                imageHolder.setIcon(format);
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
            
        String sql = "insert into Core1_PR_PatientRegistration (LastName,FirstName,MiddleName,image)values(?,?,?,?)";
            

    pst=conn.prepareStatement(sql);
    pst.setString(1, lname.getText());
    pst.setString(2, fname.getText());
    pst.setString(3, mi.getText());                  
    pst.setBytes(4, person_image);

          pst.execute();      
          lname.setText("");
          fname.setText("");
          mi.setText("");
    
      JOptionPane.showMessageDialog(null, "Saved");
      
      }
        catch(Exception e){
      JOptionPane.showMessageDialog(null, e);        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Webb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Webb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Webb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Webb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Webb().setVisible(true);
            }
        });
    }
    class VideoFeedTaker extends Thread{
    @Override
        public void run(){
            while (isRunning){
                try {
                    Image image = webcam.getImage();
                    imageHolder.setIcon(new ImageIcon(image));
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Webb.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            }
    
            
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attach_image;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel imageHolder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mi;
    private javax.swing.JTextField path;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
private ImageIcon format =null;
String filename=null;
int s=0;
byte[] person_image=null;
}
