/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module4SubModules;

import SystemInstance.MysqlConnect;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;

/**
 *
 * @author jerome
 */
public class INPATIENTADMISSION extends javax.swing.JPanel {

            GridBagLayout layout=new GridBagLayout();
            Ward sm1;
            SemiPrivate sm2;
            Private sm3;
            AdmittedHistory sm4;
            Connection conn = null;
            ResultSet rs = null;
            PreparedStatement pst = null; 
    /**
     * Creates new form SubModule1
     */
    public INPATIENTADMISSION() {
        initComponents();
        conn = MysqlConnect.ConnectDB();
        sm1 = new Ward();
        sm2 = new SemiPrivate();
        sm3 = new Private();
        sm4 = new AdmittedHistory();
        
        
        root1.setLayout(layout);
        GridBagConstraints sm11 = new GridBagConstraints();
        sm11.gridx=0;
        sm11.gridy=0;
        root1.add(sm1,sm11);
        
        root1.setLayout(layout);
        GridBagConstraints sm22 = new GridBagConstraints();
        sm22.gridx=0;
        sm22.gridy=0;
        root1.add(sm2,sm11);
        
        root1.setLayout(layout);
        GridBagConstraints sm33 = new GridBagConstraints();
        sm33.gridx=0;
        sm33.gridy=0;
        root1.add(sm3,sm11);
        
        root1.setLayout(layout);
        GridBagConstraints sm44 = new GridBagConstraints();
        sm44.gridx=0;
        sm44.gridy=0;
        root1.add(sm4,sm11);
        
        sm1.setVisible(false);
        sm2.setVisible(false);
        sm3.setVisible(false);
        sm4.setVisible(true);
    }
    public void comboselect(){
    int tmp =jComboBox1.getSelectedIndex();
        if(tmp==0){
        sm1.setVisible(true);
        sm2.setVisible(false);
        sm3.setVisible(false);
        sm4.setVisible(false);
        }
        if(tmp==1){
        sm1.setVisible(false);
        sm2.setVisible(true);
        sm3.setVisible(false);
        sm4.setVisible(false);
        } 
        if(tmp==2){
        sm1.setVisible(false);
        sm2.setVisible(false);
        sm3.setVisible(true);
        sm4.setVisible(false);
        } 
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddInpatient = new javax.swing.JDialog();
        addpatient = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        mi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        Doctorname = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        room = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        bed = new javax.swing.JComboBox<>();
        sub_module_1_btn = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        llname = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ffname = new javax.swing.JLabel();
        mmi = new javax.swing.JLabel();
        root1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        AddInpatient.setBackground(new java.awt.Color(0, 0, 255));
        AddInpatient.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        AddInpatient.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addpatient.setBackground(new java.awt.Color(204, 204, 204));
        addpatient.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                addpatientAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addpatient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Middle Initial:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 30));
        jPanel1.add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 70, 30));

        jLabel1.setText("Medic:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 30));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Public (Ward)", "Semi Private", "Private" }));
        type.setToolTipText("");
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 250, 30));

        Doctorname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Rommel Constantino", "Dr. Danilo Cacho", "Dr. Enrico Pineda", "Dr. Vincent Garados" }));
        jPanel1.add(Doctorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 250, 30));

        jLabel28.setText("Room:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 30));

        room.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room1", "Room2" }));
        jPanel1.add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 80, 30));

        jLabel29.setText("Bed:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 60, 30));

        bed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bed1", "Bed2", "Bed3", "Bed4" }));
        jPanel1.add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 80, 30));

        sub_module_1_btn.setBackground(new java.awt.Color(153, 153, 153));
        sub_module_1_btn.setText("Save & Close");
        sub_module_1_btn.setToolTipText("Sub Module 1");
        sub_module_1_btn.setBorder(null);
        sub_module_1_btn.setBorderPainted(false);
        sub_module_1_btn.setContentAreaFilled(false);
        sub_module_1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_module_1_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub_module_1_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sub_module_1_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sub_module_1_btnMouseExited(evt);
            }
        });
        sub_module_1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_module_1_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sub_module_1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, 30));

        jLabel30.setText("Type:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));
        jPanel1.add(llname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, 30));
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, 30));

        jLabel7.setText("FirstName:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 250, 30));

        jLabel8.setText("LastName:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));
        jPanel1.add(ffname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 30, 30));
        jPanel1.add(mmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 30, 30));

        addpatient.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 290));

        AddInpatient.getContentPane().add(addpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 310));

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1166, 582));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        root1.setBackground(new java.awt.Color(255, 255, 255));
        root1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(root1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, -2, 980, 580));
        root1.getAccessibleContext().setAccessibleDescription("");

        jButton1.setText("History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ward", "Semi Private", "Private" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 30));

        jLabel2.setText("Type of Rooms:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void sub_module_1_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub_module_1_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_module_1_btnMouseClicked

    private void sub_module_1_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub_module_1_btnMouseEntered
        sub_module_1_btn.setOpaque(true);
        sub_module_1_btn.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_sub_module_1_btnMouseEntered

    private void sub_module_1_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub_module_1_btnMouseExited
        sub_module_1_btn.setOpaque(false);
    }//GEN-LAST:event_sub_module_1_btnMouseExited

    private void sub_module_1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_module_1_btnActionPerformed

    }//GEN-LAST:event_sub_module_1_btnActionPerformed

    private void addpatientAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_addpatientAncestorAdded
        AddInpatient.setBounds(400,150,500,500);         // TODO add your handling code here:
    }//GEN-LAST:event_addpatientAncestorAdded

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        comboselect();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sm1.setVisible(false);
        sm2.setVisible(false);
        sm3.setVisible(false);
        sm4.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AddInpatient;
    private javax.swing.JComboBox<String> Doctorname;
    private javax.swing.JPanel addpatient;
    private javax.swing.JComboBox<String> bed;
    private javax.swing.JLabel ffname;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel llname;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mi;
    private javax.swing.JLabel mmi;
    private javax.swing.JComboBox<String> room;
    private javax.swing.JPanel root1;
    private javax.swing.JButton sub_module_1_btn;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
